
const TERMS=window.PH_DATA, CHAPTERS=window.PH_CHAPTERS, CASES=window.PH_CASES, COMM=window.PH_COMM;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem('pheng_'+k))??d}catch{return d}},set(k,v){localStorage.setItem('pheng_'+k,JSON.stringify(v))}};
let saved=store.get('saved',{}), activity=store.get('activity',{flash:0,pron:0,practice:[],cases:[],comm:[],test:[]});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const termByWord=w=>TERMS.find(t=>t.word===w);
function speak(text){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.82;speechSynthesis.speak(u)}
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-page]').forEach(b=>{const a=b.dataset.page===id;b.classList.toggle('active',a);if(a)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$$('.nav-menu-group').forEach(d=>d.open=false);location.hash=id==='home'?'':id;updateAll();window.scrollTo({top:0,behavior:'smooth'})}window.showPage=showPage;
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));
function chapterLabel(n){return `Chapter ${n} · ${CHAPTERS[n].title}`}
function updateAll(){const vals=Object.values(saved), mastered=vals.filter(x=>x.status==='mastered').length, review=vals.filter(x=>x.status==='review').length;['homeSaved','nbSaved','pSaved','navSavedCount'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=vals.length});['homeMastered','nbMastered','pMastered'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=mastered});['homeReview','nbReview'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=review});$('#pFlash').textContent=activity.flash||0;$('#pPron').textContent=activity.pron||0;$('#pCases').textContent=(activity.cases||[]).length;const pp=activity.practice||[];$('#pPractice').textContent=pp.length?Math.round(pp.slice(-3).reduce((a,x)=>a+x.score/x.total,0)/Math.min(3,pp.length)*100)+'%':'—';updatePlan();if($('#notebook').classList.contains('active'))renderNotebook();}
function saveState(){store.set('saved',saved);store.set('activity',activity);updateAll()}
function setSaved(word,status){saved[word]=saved[word]||{status:'review',seen:0}; if(status)saved[word].status=status; saveState();renderLexicon();}
function removeSaved(word){delete saved[word];saveState();renderLexicon()}

// Home
$('#statTerms').textContent=TERMS.length;$('#statChapters').textContent=Object.keys(CHAPTERS).length;$('#statSections').textContent=new Set(TERMS.map(t=>t.section)).size;
const day=Math.floor(Date.now()/86400000), spot=TERMS[day%TERMS.length];$('#spotlightContent').innerHTML=`<div class="spotlight-word">${esc(spot.word)}</div><div class="spotlight-fr">${esc(spot.fr)}</div><p>${esc(spot.definition)}</p><button onclick="speak('${spot.word.replaceAll("'","\\'")}')">🔊 Listen</button>`;
function showFive(){const five=shuffle(TERMS).slice(0,5);$('#quickWords').hidden=false;$('#quickWords').innerHTML=five.map(t=>`<article class="quick-word"><strong>${esc(t.word)}</strong><span>${esc(t.fr)}</span><p>${esc(t.definition)}</p><button onclick="speak('${t.word.replaceAll("'","\\'")}')">🔊</button></article>`).join('');$('#quickWords').scrollIntoView({behavior:'smooth'})}
$('#learnFive').onclick=showFive;$('#startHereWords').onclick=showFive;$('#quickRevision').onclick=()=>{showPage('flashcards');startFlash()};$('#fiveMinuteBoost').onclick=()=>{showPage('practice');practiceSize.value='5';startPractice()};$('#startHereTour').onclick=()=>{showPage('lexicon');query.value='';chapter.value='1';renderLexicon()};$('#surpriseMe').onclick=()=>{const pages=['lexicon','flashcards','practice','cases','communication','pronunciation'];showPage(pages[Math.floor(Math.random()*pages.length)])};

// Lexicon
const chapterSelects=['#chapter','#flashChapter'];for(const sel of chapterSelects){Object.keys(CHAPTERS).forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=chapterLabel(n);$(sel).appendChild(o)})}
[...new Set(TERMS.map(t=>t.section))].sort().forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;$('#section').appendChild(o)});
function card(t){const state=saved[t.word];return `<article class="term-card"><div class="term-head"><div><div class="badges"><span class="badge">${esc(chapterLabel(t.chapter))}</span><span class="badge">${esc(t.section)}</span><span class="badge">${esc(t.level)}</span></div><h3>${esc(t.word)}</h3><div class="ipa">${esc(t.ipa)}</div><div class="fr">${esc(t.fr)}</div></div><button onclick="speak('${t.word.replaceAll("'","\\'")}')">🔊 Listen</button></div><p>${esc(t.definition)}</p><p class="example"><strong>In context:</strong> ${esc(t.example)}</p><p><strong>Collocations:</strong> ${t.collocations.map(x=>`<span class="badge">${esc(x)}</span>`).join(' ')}</p><p><strong>Related:</strong> ${t.related.map(x=>`<span class="badge">${esc(x)}</span>`).join(' ')}</p><div class="term-actions">${state?`<button class="saved" onclick="removeSaved('${t.word.replaceAll("'","\\'")}')">♥ Saved</button><button class="${state.status==='mastered'?'mastered':''}" onclick="setSaved('${t.word.replaceAll("'","\\'")}','mastered')">✓ Mastered</button><button onclick="setSaved('${t.word.replaceAll("'","\\'")}','review')">↻ Review</button>`:`<button onclick="setSaved('${t.word.replaceAll("'","\\'")}','review')">♡ Save word</button>`}</div></article>`}
function filtered(){const q=$('#query').value.trim().toLowerCase(), ch=$('#chapter').value, sec=$('#section').value, lev=$('#level').value;return TERMS.filter(t=>(!q||JSON.stringify(t).toLowerCase().includes(q))&&(!ch||String(t.chapter)===ch)&&(!sec||t.section===sec)&&(!lev||t.level===lev))}
function renderLexicon(){const f=filtered();$('#count').textContent=`${f.length} term${f.length!==1?'s':''}`;$('#results').innerHTML=f.map(card).join('')||'<div class="panel">No matching term.</div>'}
['#query','#chapter','#section','#level'].forEach(s=>$(s).addEventListener('input',renderLexicon));renderLexicon();

// Dictionary
function dictSearch(q){q=q.trim().toLowerCase();if(q.length<2){$('#searchCount').textContent='';$('#searchResults').innerHTML='<div class="practice-welcome"><div>⌨️</div><h3>Type at least 2 characters.</h3></div>';return}const hits=TERMS.filter(t=>[t.word,t.fr,t.definition,t.example,...t.collocations,...t.related].join(' ').toLowerCase().includes(q));$('#searchCount').textContent=`${hits.length} match${hits.length!==1?'es':''}`;$('#searchResults').innerHTML=hits.slice(0,25).map(card).join('')||'<div class="panel">No match. Try another word or French equivalent.</div>'}
$('#searchInput').oninput=e=>dictSearch(e.target.value);$('#randomTerm').onclick=()=>{const t=TERMS[Math.floor(Math.random()*TERMS.length)];$('#searchInput').value=t.word;dictSearch(t.word)};

// Flashcards
let flashDeck=[],fi=0,flashStats={again:0,hard:0,got:0},flipped=false;
function sourceTerms(src){if(src==='__saved'||src==='saved')return TERMS.filter(t=>saved[t.word]);if(src==='__review'||src==='review')return TERMS.filter(t=>saved[t.word]?.status==='review');if(src&&/^\d+$/.test(src))return TERMS.filter(t=>String(t.chapter)===src);return TERMS}
function startFlash(){const pool=sourceTerms($('#flashChapter').value);const size=$('#flashSize').value==='all'?pool.length:+$('#flashSize').value;flashDeck=shuffle(pool).slice(0,size);fi=0;flashStats={again:0,hard:0,got:0};renderFlash()}
function renderFlash(){if(!flashDeck.length){$('#flash').innerHTML='<div class="panel">No cards in this deck yet.</div>';$('#flashRating').hidden=true;return}const t=flashDeck[fi];flipped=false;$('#flash').innerHTML=`<div class="flashcard" id="flashCard" tabindex="0"><div><div class="big">${esc(t.word)}</div><div class="ipa">${esc(t.ipa)}</div><p>Click or press Enter to reveal.</p><button onclick="event.stopPropagation();speak('${t.word.replaceAll("'","\\'")}')">🔊 Listen</button></div></div>`;$('#flashRating').hidden=true;$('#flashProgress').textContent=`${fi+1} / ${flashDeck.length}`;$('#flashProgressNote').textContent=chapterLabel(t.chapter);$('#flashProgressBar').style.width=((fi)/flashDeck.length*100)+'%';$('#flashAgainCount').textContent=flashStats.again;$('#flashHardCount').textContent=flashStats.hard;$('#flashGotCount').textContent=flashStats.got;$('#flashCard').onclick=flip;$('#flashCard').onkeydown=e=>{if(e.key==='Enter')flip()}}
function flip(){if(flipped)return;flipped=true;const t=flashDeck[fi];$('#flashCard').innerHTML=`<div><div class="big">${esc(t.word)}</div><div class="fr">${esc(t.fr)}</div><p>${esc(t.definition)}</p><p class="example">${esc(t.example)}</p></div>`;$('#flashRating').hidden=false}
function rateFlash(r){if(!flashDeck.length)return;const t=flashDeck[fi];flashStats[r]++;activity.flash=(activity.flash||0)+1;if(r==='got'){saved[t.word]=saved[t.word]||{};saved[t.word].status='mastered'}else if(r==='again'){saved[t.word]=saved[t.word]||{};saved[t.word].status='review'}saveState();fi=(fi+1)%flashDeck.length;renderFlash()}
$$('[data-flash-rate]').forEach(b=>b.onclick=()=>rateFlash(b.dataset.flashRate));$('#newFlashSession').onclick=startFlash;$('#next').onclick=()=>{if(flashDeck.length){fi=(fi+1)%flashDeck.length;renderFlash()}};$('#prev').onclick=()=>{if(flashDeck.length){fi=(fi-1+flashDeck.length)%flashDeck.length;renderFlash()}};$('#shuffle').onclick=()=>{flashDeck=shuffle(flashDeck);fi=0;renderFlash()};

// Practice
let practiceMode='definition',practiceDeck=[],pi=0,pcorrect=0,pmissed=0,pstreak=0,answered=false;
const modeNames={definition:'Definition Detective',french:'French → English',cloze:'Public Health Gap',listen:'Listen & Spot',collocation:'Collocation Match',mix:'Mix It Up'};
$$('[data-practice-mode]').forEach(b=>b.onclick=()=>{$$('[data-practice-mode]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');practiceMode=b.dataset.practiceMode;$('#practiceModeName').textContent=modeNames[practiceMode]});
function distractors(t,n=3){return shuffle(TERMS.filter(x=>x.word!==t.word)).slice(0,n)}
function makeQ(t,mode){if(mode==='mix')mode=shuffle(['definition','french','cloze','listen','collocation'])[0];let prompt,answer=t.word,opts;if(mode==='definition'){prompt=t.definition;opts=shuffle([t,...distractors(t)]).map(x=>x.word)}else if(mode==='french'){prompt=`Translate into professional English: “${t.fr}”`;opts=shuffle([t,...distractors(t)]).map(x=>x.word)}else if(mode==='cloze'){prompt=t.example.replace(new RegExp(t.word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'_____');opts=shuffle([t,...distractors(t)]).map(x=>x.word)}else if(mode==='listen'){prompt='Listen, then choose the term you heard.';opts=shuffle([t,...distractors(t)]).map(x=>x.word);setTimeout(()=>speak(t.word),200)}else{prompt='Choose a natural collocation with the target term: '+t.word;answer=t.collocations[0];opts=shuffle([answer,...distractors(t).map(x=>x.collocations[0])])}return{prompt,answer,opts,mode}}
function startPractice(){let pool=sourceTerms($('#practiceSource').value);if(!pool.length){$('#practiceBox').innerHTML='<div class="panel">Save some vocabulary first, or choose all vocabulary.</div>';return}practiceDeck=shuffle(pool).slice(0,Math.min(+$('#practiceSize').value,pool.length));pi=0;pcorrect=0;pmissed=0;pstreak=0;$('#practiceSessionBar').hidden=false;renderPractice()}
function renderPractice(){if(pi>=practiceDeck.length){const total=pcorrect+pmissed;activity.practice.push({score:pcorrect,total,date:Date.now()});saveState();$('#practiceBox').innerHTML=`<div class="test-score"><h3>Session complete</h3><p class="big">${pcorrect}/${total}</p><button class="primary-action" onclick="startPractice()">Play again</button></div>`;return}answered=false;const t=practiceDeck[pi],q=makeQ(t,practiceMode);$('#practiceProgress').textContent=`Question ${pi+1} / ${practiceDeck.length}`;$('#practiceCorrect').textContent=pcorrect;$('#practiceMissed').textContent=pmissed;$('#practiceStreak').textContent=pstreak;$('#practiceProgressBar').style.width=(pi/practiceDeck.length*100)+'%';$('#practiceBox').innerHTML=`<article class="practice-question"><span class="eyebrow">${esc(modeNames[q.mode]||modeNames[practiceMode])}</span><h3>${esc(q.prompt)}</h3>${q.mode==='listen'?'<button onclick="speak(\''+t.word.replaceAll("'","\\'")+'\')">🔊 Play again</button>':''}<div class="option-grid">${q.opts.map(o=>`<button data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="practiceFeedback"></div></article>`;$$('#practiceBox [data-answer]').forEach(b=>b.onclick=()=>answerPractice(b,q.answer,t))}
function answerPractice(btn,answer,t){if(answered)return;answered=true;const ok=btn.dataset.answer===answer;btn.classList.add(ok?'correct':'wrong');$$('#practiceBox [data-answer]').forEach(b=>{if(b.dataset.answer===answer)b.classList.add('correct')});if(ok){pcorrect++;pstreak++}else{pmissed++;pstreak=0;saved[t.word]=saved[t.word]||{status:'review'};saved[t.word].status='review'}$('#practiceFeedback').innerHTML=`<div class="feedback"><strong>${ok?'Correct.':'Not quite.'}</strong> ${esc(t.word)} — ${esc(t.definition)}<br><button id="practiceNext">Next →</button></div>`;saveState();$('#practiceNext').onclick=()=>{pi++;renderPractice()}}
$('#startPractice').onclick=startPractice;window.startPractice=startPractice;

// Cases
function renderCases(){const area=$('#caseArea').value,f=CASES.filter(c=>area==='all'||c.area===area);$('#caseCount').textContent=f.length;$('#caseGrid').innerHTML=f.map((c,i)=>`<article class="case-card"><span class="eyebrow">${esc(c.area)}</span><h3>${esc(c.title)}</h3><p>${esc(c.scenario)}</p><button class="primary-action" data-case="${CASES.indexOf(c)}">Open case →</button></article>`).join('');$$('[data-case]').forEach(b=>b.onclick=()=>openCase(+b.dataset.case))}
function openCase(i){const c=CASES[i],mode=$('#caseDifficulty').value;$('#caseWorkspace').hidden=false;$('#caseWorkspace').innerHTML=`<button class="workspace-close" onclick="caseWorkspace.hidden=true">× Close</button><span class="eyebrow">${esc(c.area)} · ${esc(mode)}</span><h3>${esc(c.title)}</h3><p>${esc(c.scenario)}</p><div class="support-box"><strong>Your task</strong><p>${esc(c.prompt)}</p>${mode==='guided'?`<p><strong>Useful terms:</strong> ${c.terms.map(x=>`<span class="badge">${esc(x)}</span>`).join(' ')}</p>`:''}</div><textarea id="caseAnswer" rows="7" style="width:100%" placeholder="Write or prepare your answer here. Nothing is uploaded."></textarea><div class="card-actions"><button id="revealCase">Reveal model</button><button id="doneCase">Mark as explored</button></div><div id="caseModel"></div>`;$('#caseWorkspace').scrollIntoView({behavior:'smooth'});$('#revealCase').onclick=()=>$('#caseModel').innerHTML=`<div class="model"><strong>Possible model</strong><p>${esc(c.model)}</p></div>`;$('#doneCase').onclick=()=>{activity.cases=[...new Set([...(activity.cases||[]),i])];saveState();$('#doneCase').textContent='✓ Explored'}}
$('#caseArea').onchange=renderCases;$('#caseDifficulty').onchange=renderCases;$('#randomCase').onclick=()=>openCase(Math.floor(Math.random()*CASES.length));renderCases();

// Communication
function renderComm(){const sk=$('#communicationSkill').value,f=COMM.filter(c=>sk==='all'||c.skill===sk);$('#communicationCount').textContent=f.length;$('#communicationGrid').innerHTML=f.map(c=>`<article class="comm-card"><span class="eyebrow">${esc(c.skill)}</span><h3>${esc(c.title)}</h3><p>${esc(c.prompt)}</p><button class="primary-action" data-comm="${COMM.indexOf(c)}">Open task →</button></article>`).join('');$$('[data-comm]').forEach(b=>b.onclick=()=>openComm(+b.dataset.comm))}
function openComm(i){const c=COMM[i],mode=$('#communicationMode').value;$('#communicationWorkspace').hidden=false;$('#communicationWorkspace').innerHTML=`<button class="workspace-close" onclick="communicationWorkspace.hidden=true">× Close</button><span class="eyebrow">${esc(c.skill)} · ${esc(mode)}</span><h3>${esc(c.title)}</h3><p>${esc(c.prompt)}</p>${mode==='guided'?`<div class="support-box"><strong>Useful language</strong>${c.support.map(x=>`<p>• ${esc(x)}</p>`).join('')}</div>`:''}<textarea rows="7" style="width:100%" placeholder="Prepare your answer here. Nothing is uploaded."></textarea><div class="card-actions"><button id="revealComm">Reveal model</button><button id="doneComm">Mark as explored</button></div><div id="commModel"></div>`;$('#communicationWorkspace').scrollIntoView({behavior:'smooth'});$('#revealComm').onclick=()=>$('#commModel').innerHTML=`<div class="model"><strong>Possible model</strong><p>${esc(c.model)}</p></div>`;$('#doneComm').onclick=()=>{activity.comm=[...new Set([...(activity.comm||[]),i])];saveState();$('#doneComm').textContent='✓ Explored'}}
$('#communicationSkill').onchange=renderComm;$('#communicationMode').onchange=renderComm;$('#randomCommunication').onclick=()=>openComm(Math.floor(Math.random()*COMM.length));renderComm();

// Pronunciation
const tricky=TERMS.filter(t=>t.word.length>15||/epidemi|pharmaco|random|validity|significance|inequal|determinant|environment/i.test(t.word));let pronDeck=[],pri=0;
function pronPool(){const s=$('#pronSource').value;if(s==='tricky')return tricky;if(s==='review')return TERMS.filter(t=>saved[t.word]?.pron==='review');return TERMS}
function startPron(){pronDeck=shuffle(pronPool()).slice(0,+$('#pronSize').value);pri=0;renderPron()}
function renderPron(){
  if(!pronDeck.length){
    $('#pronWorkspace').innerHTML='<div class="practice-welcome"><h3>No words in this set yet.</h3></div>';
    return;
  }
  const t=pronDeck[pri];
  $('#pronWorkspace').innerHTML=`<div class="pron-card"><div class="pron-progress">${pri+1} / ${pronDeck.length} · ${esc(chapterLabel(t.chapter))}</div><div class="pron-word">${esc(t.word)}</div><div class="pron-ipa">${esc(t.ipa)}</div><p>${esc(t.example)}</p><button class="primary-action" onclick="speak('${t.word.replaceAll("'","\\'")}')">🔊 Listen in British English</button><div class="pron-ratings"><button data-pr="easy">✓ Easy</button><button data-pr="tricky">◐ Tricky</button><button data-pr="review">↻ Again</button></div></div>`;
  $$('[data-pr]').forEach(b=>{
    b.onclick=()=>{
      saved[t.word]=saved[t.word]||{status:'review'};
      saved[t.word].pron=b.dataset.pr;
      activity.pron=(activity.pron||0)+1;
      saveState();
      pri++;
      if(pri>=pronDeck.length){
        $('#pronWorkspace').innerHTML='<div class="test-score"><h3>Workout complete.</h3><button class="primary-action" id="pronAgain">New workout</button></div>';
        $('#pronAgain').onclick=startPron;
      }else{
        renderPron();
      }
    };
  });
}
$('#startPron').onclick=startPron;$('#startPronQuick').onclick=()=>{$('#pronSource').value='tricky';$('#pronSize').value='5';startPron()};$('#randomPronWord').onclick=()=>{pronDeck=[tricky[Math.floor(Math.random()*tricky.length)]];pri=0;renderPron()};

// Notebook
function renderNotebook(){const q=$('#notebookSearch').value.toLowerCase(),st=$('#notebookStatus').value;let f=TERMS.filter(t=>saved[t.word]).filter(t=>!q||JSON.stringify(t).toLowerCase().includes(q)).filter(t=>st==='all'||saved[t.word].status===st);$('#notebookResults').innerHTML=f.map(card).join('')||'<div class="panel">No saved words match these filters.</div>'}
$('#notebookSearch').oninput=renderNotebook;$('#notebookStatus').onchange=renderNotebook;$('#clearNotebook').onclick=()=>{if(confirm('Clear all saved vocabulary and word ratings on this device?')){saved={};saveState();renderNotebook();renderLexicon()}};$('#exportNotebook').onclick=()=>{const rows=[['English','IPA','French','Status'],...TERMS.filter(t=>saved[t.word]).map(t=>[t.word,t.ipa,t.fr,saved[t.word].status])];const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='my-public-health-vocabulary.csv';a.click();URL.revokeObjectURL(a.href)};

// Progress
function updatePlan(){const vals=Object.values(saved),review=vals.filter(x=>x.status==='review').length;let title,text,page='lexicon';if(review>=5){title='Revisit your difficult vocabulary.';text=`You have ${review} saved words marked for review. A focused flashcard session is the best next step.`;page='flashcards'}else if(!(activity.practice||[]).length){title='Test active recall.';text='You have explored vocabulary, but there is no recent practice session yet. Try five mixed questions.';page='practice'}else if(!(activity.cases||[]).length){title='Move from vocabulary to reasoning.';text='Try one Public Health Case and use the terminology in context.';page='cases'}else{title='Practise communicating evidence.';text='Use one Communication Lab task to turn methods and data into clear professional English.';page='communication'}$('#planTitle').textContent=title;$('#planText').textContent=text;$('#planAction').onclick=()=>showPage(page);$('#continueLearningTitle').textContent=title;$('#continueLearningText').textContent=text;$('#continueLearningAction').onclick=()=>showPage(page)}

// Check-up
let testDeck=[],ti=0,tscore=0,testWrong=[];
function buildTest(){const chapterBuckets=Object.keys(CHAPTERS).flatMap(ch=>shuffle(TERMS.filter(t=>String(t.chapter)===ch)).slice(0,2));const extras=shuffle(TERMS.filter(t=>!chapterBuckets.includes(t))).slice(0,4);return shuffle([...chapterBuckets,...extras]).slice(0,24)}
function renderTest(){if(ti>=testDeck.length){activity.test.push({score:tscore,total:testDeck.length,date:Date.now()});testWrong.forEach(t=>{saved[t.word]=saved[t.word]||{};saved[t.word].status='review'});saveState();$('#testBox').innerHTML=`<div class="test-score"><h3>Check-up complete</h3><div class="big">${tscore}/${testDeck.length}</div><p>${tscore>=20?'Strong result. Keep using the Communication Lab and cases.':tscore>=15?'Solid base. Review the missed terms, then try again later.':'Use the missed terms as a focused revision deck.'}</p><button onclick="showPage('notebook')">Review saved words</button> <button class="primary-action" onclick="startTestRun()">Try another check-up</button></div>`;return}const t=testDeck[ti],mode=ti%3===0?'french':'definition',q=makeQ(t,mode);$('#testBox').innerHTML=`<article class="test-question"><span class="eyebrow">Question ${ti+1} / ${testDeck.length}</span><h3>${esc(q.prompt)}</h3><div class="option-grid">${q.opts.map(o=>`<button data-test-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="testFeedback"></div></article>`;$$('[data-test-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.testAnswer===q.answer;if(ok)tscore++;else testWrong.push(t);b.classList.add(ok?'correct':'wrong');$$('[data-test-answer]').forEach(x=>{if(x.dataset.testAnswer===q.answer)x.classList.add('correct');x.disabled=true});$('#testFeedback').innerHTML=`<div class="feedback"><strong>${ok?'Correct.':'Answer: '+esc(q.answer)}</strong><br><button id="nextTest">Next →</button></div>`;$('#nextTest').onclick=()=>{ti++;renderTest()}})}
function startTestRun(){testDeck=buildTest();ti=0;tscore=0;testWrong=[];renderTest()}window.startTestRun=startTestRun;$('#startTest').onclick=startTestRun;

// Accessibility & PWA
let scale=store.get('scale',1);document.documentElement.style.setProperty('--scale',scale);$('#aMinus').onclick=()=>{scale=Math.max(.85,scale-.1);document.documentElement.style.setProperty('--scale',scale);store.set('scale',scale)};$('#aPlus').onclick=()=>{scale=Math.min(1.5,scale+.1);document.documentElement.style.setProperty('--scale',scale);store.set('scale',scale)};
function toggleData(attr,val){const root=document.documentElement;if(root.getAttribute(attr)===val)root.removeAttribute(attr);else root.setAttribute(attr,val)}$('#dark').onclick=()=>toggleData('data-theme','dark');$('#contrast').onclick=()=>toggleData('data-contrast','high');$('#simple').onclick=()=>document.body.classList.toggle('simple');$('#motion').onclick=()=>document.body.classList.toggle('reduce-motion');
window.addEventListener('online',()=>{$('#connectionStatus').innerHTML='<span>●</span> Online';$('#connectionStatus').className='connection-status is-online'});window.addEventListener('offline',()=>{$('#connectionStatus').innerHTML='<span>●</span> Offline';$('#connectionStatus').className='connection-status'});
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installApp').disabled=false;$('#headerInstallApp').disabled=false});async function install(){if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else{$('#installHelpPanel').hidden=false;showPage('home');$('#installCard').scrollIntoView({behavior:'smooth'})}}$('#installApp').onclick=install;$('#headerInstallApp').onclick=install;$('#installHelp').onclick=()=>$('#installHelpPanel').hidden=!$('#installHelpPanel').hidden;if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
window.speak=speak;window.setSaved=setSaved;window.removeSaved=removeSaved;
const hash=location.hash.replace('#','');if(hash&&$('#'+hash))showPage(hash);updateAll();