
const TERMS=Array.isArray(window.PH_DATA)?window.PH_DATA:[], CHAPTERS=window.PH_CHAPTERS||{}, CASES=Array.isArray(window.PH_CASES)?window.PH_CASES:[], COMM=Array.isArray(window.PH_COMM)?window.PH_COMM:[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem('pheng_'+k))??d}catch{return d}},set(k,v){try{localStorage.setItem('pheng_'+k,JSON.stringify(v));return true}catch{return false}}};
const activityDefaults={flash:0,pron:0,practice:[],cases:[],comm:[],group:[],test:[]};
let saved=store.get('saved',{});if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};
let pronRatings=store.get('pronRatings',{});if(!pronRatings||typeof pronRatings!=='object'||Array.isArray(pronRatings))pronRatings={};for(const [word,state] of Object.entries(saved)){if(state?.pron&&!pronRatings[word])pronRatings[word]=state.pron}
let activity={...activityDefaults,...store.get('activity',{})};
for(const key of ['practice','cases','comm','group','test'])if(!Array.isArray(activity[key]))activity[key]=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const prefersReducedMotion=()=>document.body.classList.contains('reduce-motion')||(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches);
const scrollBehavior=()=>prefersReducedMotion()?'auto':'smooth';
const termByWord=w=>TERMS.find(t=>t.word===w);
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';const voices=speechSynthesis.getVoices?.()||[];const british=voices.find(v=>String(v.lang).toLowerCase()==='en-gb')||voices.find(v=>String(v.lang).toLowerCase().startsWith('en-gb'));if(british)u.voice=british;u.rate=.82;speechSynthesis.speak(u)}
function showPage(id,fromHistory=false){const target=$('#'+id);if(!target?.classList.contains('page'))id='home';$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-page]').forEach(b=>{const a=b.dataset.page===id;b.classList.toggle('active',a);if(a)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$$('.nav-menu-group').forEach(d=>{d.open=false;const pages=(d.dataset.navPages||'').split(',');d.classList.toggle('active',pages.includes(id))});if(!fromHistory){const wanted=id==='home'?'':'#'+id;if(location.hash!==wanted)location.hash=wanted}updateAll();window.scrollTo({top:0,behavior:scrollBehavior()})}window.showPage=showPage;
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));
function chapterLabel(n){return CHAPTERS[n]?`Chapter ${n} · ${CHAPTERS[n].title}`:`Chapter ${n}`}
function updateAll(){const vals=Object.values(saved), mastered=vals.filter(x=>x.status==='mastered').length, review=vals.filter(x=>x.status==='review').length, pronVals=Object.values(pronRatings), pronRated=pronVals.length, pronReview=pronVals.filter(x=>x==='review'||x==='tricky').length;['homeSaved','nbSaved','pSaved','navSavedCount'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=vals.length});['homeMastered','nbMastered','pMastered'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=mastered});['homeReview','nbReview'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=review});const setText=(id,value)=>{const e=$('#'+id);if(e)e.textContent=value};setText('pFlash',activity.flash||0);setText('pPron',activity.pron||0);setText('pCases',activity.cases.length);setText('pComm',activity.comm.length);setText('pGroup',activity.group.length);setText('pronRated',pronRated);setText('pronReview',pronReview);setText('groupCompletedCount',activity.group.length);const pp=activity.practice||[];const recent=pp.slice(-3).filter(x=>x&&x.total>0);setText('pPractice',recent.length?Math.round(recent.reduce((a,x)=>a+x.score/x.total,0)/recent.length*100)+'%':'—');updatePlan();if($('#notebook')?.classList.contains('active'))renderNotebook();}
function saveState(){store.set('saved',saved);store.set('pronRatings',pronRatings);store.set('activity',activity);updateAll()}
function refreshDictionary(){if($('#search')?.classList.contains('active'))dictSearch($('#searchInput').value)}
function setSaved(word,status){saved[word]=saved[word]||{status:'review',seen:0};if(status)saved[word].status=status;saveState();renderLexicon();refreshDictionary()}
function removeSaved(word){delete saved[word];saveState();renderLexicon();refreshDictionary()}

// Home
$('#statTerms').textContent=TERMS.length;$('#statChapters').textContent=Object.keys(CHAPTERS).length;$('#statSections').textContent=new Set(TERMS.map(t=>t.section)).size;
const day=Math.floor(Date.now()/86400000), spot=TERMS.length?TERMS[day%TERMS.length]:null;if(spot)$('#spotlightContent').innerHTML=`<div class="spotlight-word">${esc(spot.word)}</div><div class="spotlight-fr">${esc(spot.fr)}</div><p>${esc(spot.definition)}</p><button onclick="speak('${spot.word.replaceAll("'","\\'")}')">🔊 Listen</button>`;else $('#spotlightContent').innerHTML='<p>Vocabulary data could not be loaded.</p>';
function showFive(){const five=shuffle(TERMS).slice(0,5);$('#quickWords').hidden=false;$('#quickWords').innerHTML=five.map(t=>`<article class="quick-word"><strong>${esc(t.word)}</strong><span>${esc(t.fr)}</span><p>${esc(t.definition)}</p><button onclick="speak('${t.word.replaceAll("'","\\'")}')">🔊</button></article>`).join('');$('#quickWords').scrollIntoView({behavior:scrollBehavior()})}
$('#learnFive').onclick=showFive;$('#startHereWords').onclick=showFive;$('#quickRevision').onclick=()=>{showPage('flashcards');startFlash()};$('#fiveMinuteBoost').onclick=()=>{showPage('practice');$('#practiceSize').value='5';startPractice()};$('#startHereTour').onclick=()=>{showPage('lexicon');$('#query').value='';$('#chapter').value='1';renderLexicon()};$('#surpriseMe').onclick=()=>{const pages=['lexicon','flashcards','practice','cases','communication','groupactivity','pronunciation'];showPage(pages[Math.floor(Math.random()*pages.length)])};

// Lexicon
const chapterSelects=['#chapter','#flashChapter'];for(const sel of chapterSelects){Object.keys(CHAPTERS).forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=chapterLabel(n);$(sel).appendChild(o)})}
[...new Set(TERMS.map(t=>t.section))].sort().forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;$('#section').appendChild(o)});
function card(t){const state=saved[t.word];return `<article class="term-card"><div class="term-head"><div><div class="badges"><span class="badge">${esc(chapterLabel(t.chapter))}</span><span class="badge">${esc(t.section)}</span><span class="badge">${esc(t.level)}</span></div><h3>${esc(t.word)}</h3><div class="ipa">${esc(t.ipa)}</div><div class="fr">${esc(t.fr)}</div></div><button onclick="speak('${t.word.replaceAll("'","\\'")}')">🔊 Listen</button></div><p>${esc(t.definition)}</p><p class="example"><strong>In context:</strong> ${esc(t.example)}</p><p><strong>Collocations:</strong> ${t.collocations.map(x=>`<span class="badge">${esc(x)}</span>`).join(' ')}</p><p><strong>Related:</strong> ${t.related.map(x=>`<span class="badge">${esc(x)}</span>`).join(' ')}</p><div class="term-actions">${state?`<button class="saved" onclick="removeSaved('${t.word.replaceAll("'","\\'")}')">♥ Saved</button><button class="${state.status==='mastered'?'mastered':''}" onclick="setSaved('${t.word.replaceAll("'","\\'")}','mastered')">✓ Mastered</button><button onclick="setSaved('${t.word.replaceAll("'","\\'")}','review')">↻ Review</button>`:`<button onclick="setSaved('${t.word.replaceAll("'","\\'")}','review')">♡ Save word</button>`}</div></article>`}
function filtered(){const q=$('#query').value.trim().toLowerCase(), ch=$('#chapter').value, sec=$('#section').value, lev=$('#level').value;return TERMS.filter(t=>(!q||JSON.stringify(t).toLowerCase().includes(q))&&(!ch||String(t.chapter)===ch)&&(!sec||t.section===sec)&&(!lev||t.level===lev))}
function renderLexicon(){const f=filtered();$('#count').textContent=`${f.length} term${f.length!==1?'s':''}`;$('#results').innerHTML=f.map(card).join('')||'<div class="panel">No matching term.</div>'}
['#query','#chapter','#section','#level'].forEach(s=>$(s).addEventListener('input',renderLexicon));renderLexicon();

// Dictionary
function dictSearch(q){q=q.trim().toLowerCase();if(q.length<2){$('#searchCount').textContent='';$('#searchResults').innerHTML='<div class="practice-welcome"><div>⌨️</div><h3>Type at least 2 characters.</h3></div>';return}const hits=TERMS.filter(t=>[t.word,t.fr,t.definition,t.example,...t.collocations,...t.related].join(' ').toLowerCase().includes(q));$('#searchCount').textContent=`${hits.length} match${hits.length!==1?'es':''}`;$('#searchResults').innerHTML=hits.slice(0,25).map(card).join('')||'<div class="panel">No match. Try another word or French equivalent.</div>'}
$('#searchInput').oninput=e=>dictSearch(e.target.value);$('#randomTerm').onclick=()=>{if(!TERMS.length)return;const t=TERMS[Math.floor(Math.random()*TERMS.length)];$('#searchInput').value=t.word;dictSearch(t.word)};

// Flashcards
let flashDeck=[],fi=0,flashStats={again:0,hard:0,got:0},flashRatingsThisSession={},flipped=false;
function sourceTerms(src){if(src==='__saved'||src==='saved')return TERMS.filter(t=>saved[t.word]);if(src==='__review'||src==='review')return TERMS.filter(t=>saved[t.word]?.status==='review');if(src&&/^\d+$/.test(src))return TERMS.filter(t=>String(t.chapter)===src);return TERMS}
function startFlash(){const pool=sourceTerms($('#flashChapter').value);const size=$('#flashSize').value==='all'?pool.length:+$('#flashSize').value;flashDeck=shuffle(pool).slice(0,size);fi=0;flashStats={again:0,hard:0,got:0};flashRatingsThisSession={};renderFlash()}
function renderFlash(){if(!flashDeck.length){$('#flash').innerHTML='<div class="panel">No cards in this deck yet.</div>';$('#flashRating').hidden=true;$('#flashProgress').textContent='0 / 0';$('#flashProgressBar').style.width='0%';return}const t=flashDeck[fi];flipped=false;$('#flash').innerHTML=`<div class="flashcard" id="flashCard" tabindex="0" role="button" aria-label="Reveal ${esc(t.word)}"><div><div class="big">${esc(t.word)}</div><div class="ipa">${esc(t.ipa)}</div><p>Click, press Enter or press Space to reveal.</p><button type="button" onclick="event.stopPropagation();speak('${t.word.replaceAll("'","\\'")}')">🔊 Listen</button></div></div>`;$('#flashRating').hidden=true;$('#flashProgress').textContent=`${fi+1} / ${flashDeck.length}`;$('#flashProgressNote').textContent=chapterLabel(t.chapter);$('#flashProgressBar').style.width=((fi+1)/flashDeck.length*100)+'%';$('#flashAgainCount').textContent=flashStats.again;$('#flashHardCount').textContent=flashStats.hard;$('#flashGotCount').textContent=flashStats.got;$('#flashCard').onclick=flip;$('#flashCard').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip()}}}
function flip(){if(flipped||!flashDeck.length)return;flipped=true;const t=flashDeck[fi];$('#flashCard').setAttribute('aria-label',`Definition of ${t.word}`);$('#flashCard').innerHTML=`<div><div class="big">${esc(t.word)}</div><div class="fr">${esc(t.fr)}</div><p>${esc(t.definition)}</p><p class="example">${esc(t.example)}</p></div>`;$('#flashRating').hidden=false}
function finishFlash(){if(!flashDeck.length)return;$('#flashRating').hidden=true;$('#flashProgress').textContent=`${flashDeck.length} / ${flashDeck.length}`;$('#flashProgressNote').textContent='Session complete.';$('#flashProgressBar').style.width='100%';$('#flashAgainCount').textContent=flashStats.again;$('#flashHardCount').textContent=flashStats.hard;$('#flashGotCount').textContent=flashStats.got;$('#flash').innerHTML=`<div class="test-score"><h3>Flashcard session complete</h3><p><strong>${flashStats.got}</strong> got it · <strong>${flashStats.hard}</strong> hard · <strong>${flashStats.again}</strong> again</p><p>Difficult words have been kept in your review list.</p><button class="primary-action" id="flashAgain">Start a new session</button></div>`;$('#flashAgain').onclick=startFlash}
function advanceFlash(){if(!flashDeck.length)return;fi++;if(fi>=flashDeck.length)finishFlash();else renderFlash()}
function rateFlash(r){if(!flashDeck.length||fi>=flashDeck.length)return;const t=flashDeck[fi],previous=flashRatingsThisSession[t.word];if(previous&&flashStats[previous]>0)flashStats[previous]--;else activity.flash=(activity.flash||0)+1;flashRatingsThisSession[t.word]=r;flashStats[r]++;saved[t.word]=saved[t.word]||{status:'review'};if(r==='got')saved[t.word].status='mastered';else saved[t.word].status='review';saveState();advanceFlash()}
$$('[data-flash-rate]').forEach(b=>b.onclick=()=>rateFlash(b.dataset.flashRate));$('#newFlashSession').onclick=startFlash;$('#next').onclick=advanceFlash;$('#prev').onclick=()=>{if(flashDeck.length&&fi>0){fi--;renderFlash()}};$('#shuffle').onclick=()=>{if(flashDeck.length&&fi<flashDeck.length){flashDeck=[...flashDeck.slice(0,fi),...shuffle(flashDeck.slice(fi))];renderFlash()}};

// Practice
let practiceMode='definition',practiceDeck=[],pi=0,pcorrect=0,pmissed=0,pstreak=0,answered=false;
const modeNames={definition:'Definition Detective',french:'French → English',cloze:'Public Health Gap',listen:'Listen & Spot',collocation:'Collocation Match',mix:'Mix It Up'};
$$('[data-practice-mode]').forEach(b=>b.onclick=()=>{$$('[data-practice-mode]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');practiceMode=b.dataset.practiceMode;$('#practiceModeName').textContent=modeNames[practiceMode]});
function distractors(t,n=3){return shuffle(TERMS.filter(x=>x.word!==t.word)).slice(0,n)}
function makeQ(t,mode){if(mode==='mix')mode=shuffle(['definition','french','cloze','listen','collocation'])[0];let prompt,answer=t.word,opts;if(mode==='definition'){prompt=t.definition;opts=shuffle([t,...distractors(t)]).map(x=>x.word)}else if(mode==='french'){prompt=`Translate into professional English: “${t.fr}”`;opts=shuffle([t,...distractors(t)]).map(x=>x.word)}else if(mode==='cloze'){const re=new RegExp(t.word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');prompt=t.example.replace(re,'_____');if(prompt===t.example)prompt=`Which term best fits this public-health context? ${t.example}`;opts=shuffle([t,...distractors(t)]).map(x=>x.word)}else if(mode==='listen'){prompt='Listen, then choose the term you heard.';opts=shuffle([t,...distractors(t)]).map(x=>x.word);setTimeout(()=>speak(t.word),200)}else{prompt='Choose a natural collocation with the target term: '+t.word;answer=t.collocations[0];const candidates=shuffle(TERMS.filter(x=>x.word!==t.word).map(x=>x.collocations?.[0]).filter(x=>x&&x!==answer));opts=shuffle([answer,...[...new Set(candidates)].slice(0,3)])}return{prompt,answer,opts,mode}}
function startPractice(){let pool=sourceTerms($('#practiceSource').value);if(!pool.length){$('#practiceBox').innerHTML='<div class="panel">Save some vocabulary first, or choose all vocabulary.</div>';return}practiceDeck=shuffle(pool).slice(0,Math.min(+$('#practiceSize').value,pool.length));pi=0;pcorrect=0;pmissed=0;pstreak=0;$('#practiceSessionBar').hidden=false;renderPractice()}
function renderPractice(){if(pi>=practiceDeck.length){const total=pcorrect+pmissed;activity.practice.push({score:pcorrect,total,date:Date.now()});$('#practiceProgress').textContent=`Session complete · ${total} question${total!==1?'s':''}`;$('#practiceCorrect').textContent=pcorrect;$('#practiceMissed').textContent=pmissed;$('#practiceStreak').textContent=pstreak;$('#practiceProgressBar').style.width='100%';saveState();$('#practiceBox').innerHTML=`<div class="test-score"><h3>Session complete</h3><p class="big">${pcorrect}/${total}</p><button class="primary-action" onclick="startPractice()">Play again</button></div>`;return}answered=false;const t=practiceDeck[pi],q=makeQ(t,practiceMode);$('#practiceProgress').textContent=`Question ${pi+1} / ${practiceDeck.length}`;$('#practiceCorrect').textContent=pcorrect;$('#practiceMissed').textContent=pmissed;$('#practiceStreak').textContent=pstreak;$('#practiceProgressBar').style.width=((pi+1)/practiceDeck.length*100)+'%';$('#practiceBox').innerHTML=`<article class="practice-question"><span class="eyebrow">${esc(modeNames[q.mode]||modeNames[practiceMode])}</span><h3>${esc(q.prompt)}</h3>${q.mode==='listen'?'<button onclick="speak(\''+t.word.replaceAll("'","\\'")+'\')">🔊 Play again</button>':''}<div class="option-grid">${q.opts.map(o=>`<button data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="practiceFeedback"></div></article>`;$$('#practiceBox [data-answer]').forEach(b=>b.onclick=()=>answerPractice(b,q.answer,t))}
function answerPractice(btn,answer,t){if(answered)return;answered=true;const ok=btn.dataset.answer===answer;btn.classList.add(ok?'correct':'wrong');$$('#practiceBox [data-answer]').forEach(b=>{if(b.dataset.answer===answer)b.classList.add('correct');b.disabled=true});if(ok){pcorrect++;pstreak++}else{pmissed++;pstreak=0;saved[t.word]=saved[t.word]||{status:'review'};saved[t.word].status='review'}$('#practiceFeedback').innerHTML=`<div class="feedback"><strong>${ok?'Correct.':'Not quite.'}</strong> ${esc(t.word)} — ${esc(t.definition)}<br><button id="practiceNext">Next →</button></div>`;saveState();$('#practiceNext').onclick=()=>{pi++;renderPractice()}}
$('#startPractice').onclick=startPractice;window.startPractice=startPractice;

// Cases
function renderCases(){const area=$('#caseArea').value,f=CASES.filter(c=>area==='all'||c.area===area);$('#caseCount').textContent=f.length;$('#caseGrid').innerHTML=f.map((c,i)=>`<article class="case-card"><span class="eyebrow">${esc(c.area)}</span><h3>${esc(c.title)}</h3><p>${esc(c.scenario)}</p><button class="primary-action" data-case="${CASES.indexOf(c)}">Open case →</button></article>`).join('');$$('[data-case]').forEach(b=>b.onclick=()=>openCase(+b.dataset.case))}
function openCase(i){const c=CASES[i],mode=$('#caseDifficulty').value;$('#caseWorkspace').hidden=false;$('#caseWorkspace').innerHTML=`<button class="workspace-close" id="closeCaseWorkspace" type="button">× Close</button><span class="eyebrow">${esc(c.area)} · ${esc(mode)}</span><h3>${esc(c.title)}</h3><p>${esc(c.scenario)}</p><div class="support-box"><strong>Your task</strong><p>${esc(c.prompt)}</p>${mode==='guided'?`<p><strong>Useful terms:</strong> ${c.terms.map(x=>`<span class="badge">${esc(x)}</span>`).join(' ')}</p>`:''}</div><textarea id="caseAnswer" rows="7" style="width:100%" placeholder="Write or prepare your answer here. Nothing is uploaded."></textarea><div class="card-actions"><button id="revealCase">Reveal model</button><button id="doneCase">Mark as explored</button></div><div id="caseModel"></div>`;$('#closeCaseWorkspace').onclick=()=>{$('#caseWorkspace').hidden=true};$('#caseWorkspace').scrollIntoView({behavior:scrollBehavior()});$('#revealCase').onclick=()=>$('#caseModel').innerHTML=`<div class="model"><strong>Possible model</strong><p>${esc(c.model)}</p></div>`;$('#doneCase').onclick=()=>{activity.cases=[...new Set([...(activity.cases||[]),i])];saveState();$('#doneCase').textContent='✓ Explored'}}
function closeCaseWorkspace(){if($('#caseWorkspace'))$('#caseWorkspace').hidden=true}$('#caseArea').onchange=()=>{closeCaseWorkspace();renderCases()};$('#caseDifficulty').onchange=()=>{closeCaseWorkspace();renderCases()};$('#randomCase').onclick=()=>{if(CASES.length)openCase(Math.floor(Math.random()*CASES.length))};renderCases();

// Communication
function renderComm(){const sk=$('#communicationSkill').value,f=COMM.filter(c=>sk==='all'||c.skill===sk);$('#communicationCount').textContent=f.length;$('#communicationGrid').innerHTML=f.map(c=>`<article class="comm-card"><span class="eyebrow">${esc(c.skill)}</span><h3>${esc(c.title)}</h3><p>${esc(c.prompt)}</p><button class="primary-action" data-comm="${COMM.indexOf(c)}">Open task →</button></article>`).join('');$$('[data-comm]').forEach(b=>b.onclick=()=>openComm(+b.dataset.comm))}
function openComm(i){const c=COMM[i],mode=$('#communicationMode').value;$('#communicationWorkspace').hidden=false;$('#communicationWorkspace').innerHTML=`<button class="workspace-close" id="closeCommunicationWorkspace" type="button">× Close</button><span class="eyebrow">${esc(c.skill)} · ${esc(mode)}</span><h3>${esc(c.title)}</h3><p>${esc(c.prompt)}</p>${mode==='guided'?`<div class="support-box"><strong>Useful language</strong>${c.support.map(x=>`<p>• ${esc(x)}</p>`).join('')}</div>`:''}<textarea rows="7" style="width:100%" placeholder="Prepare your answer here. Nothing is uploaded."></textarea><div class="card-actions"><button id="revealComm">Reveal model</button><button id="doneComm">Mark as explored</button></div><div id="commModel"></div>`;$('#closeCommunicationWorkspace').onclick=()=>{$('#communicationWorkspace').hidden=true};$('#communicationWorkspace').scrollIntoView({behavior:scrollBehavior()});$('#revealComm').onclick=()=>$('#commModel').innerHTML=`<div class="model"><strong>Possible model</strong><p>${esc(c.model)}</p></div>`;$('#doneComm').onclick=()=>{activity.comm=[...new Set([...(activity.comm||[]),i])];saveState();$('#doneComm').textContent='✓ Explored'}}
function closeCommunicationWorkspace(){if($('#communicationWorkspace'))$('#communicationWorkspace').hidden=true}$('#communicationSkill').onchange=()=>{closeCommunicationWorkspace();renderComm()};$('#communicationMode').onchange=()=>{closeCommunicationWorkspace();renderComm()};$('#randomCommunication').onclick=()=>{if(COMM.length)openComm(Math.floor(Math.random()*COMM.length))};renderComm();

// Pronunciation
const tricky=TERMS.filter(t=>t.word.length>15||/epidemi|pharmaco|random|validity|significance|inequal|determinant|environment/i.test(t.word));let pronDeck=[],pri=0;
function pronPool(){const s=$('#pronSource').value;if(s==='tricky')return tricky;if(s==='review')return TERMS.filter(t=>pronRatings[t.word]==='review'||pronRatings[t.word]==='tricky');return TERMS}
function startPron(){pronDeck=shuffle(pronPool()).slice(0,+$('#pronSize').value);pri=0;renderPron()}
function renderPron(){
  if(!pronDeck.length){
    $('#pronWorkspace').innerHTML='<div class="practice-welcome"><h3>No words in this set yet.</h3></div>';
    return;
  }
  const t=pronDeck[pri];
  $('#pronWorkspace').innerHTML=`<div class="pron-card"><div class="pron-progress">${pri+1} / ${pronDeck.length} · ${esc(chapterLabel(t.chapter))}</div><div class="pron-word">${esc(t.word)}</div><div class="pron-ipa">${esc(t.ipa)}</div><p>${esc(t.example)}</p><button class="primary-action" onclick="speak('${t.word.replaceAll("'","\\'")}')">🔊 Listen in British English</button><div class="pron-ratings"><button data-pr="easy">✓ Easy</button><button data-pr="tricky">◐ Tricky</button><button data-pr="review">↻ Again</button></div></div>`;
  $$('[data-pr]').forEach(b=>{
    b.onclick=()=>{
      pronRatings[t.word]=b.dataset.pr;
      activity.pron=(activity.pron||0)+1;
      saveState();
      pri++;
      if(pri>=pronDeck.length){
        $('#pronWorkspace').innerHTML='<div class="test-score"><h3>Workout complete.</h3><button class="primary-action" id="pronAgain">New workout</button></div>';
        $('#pronAgain').onclick=startPron;
      }else{
        renderPron();
      }
    };
  });
}
$('#startPron').onclick=startPron;$('#startPronQuick').onclick=()=>{$('#pronSource').value='tricky';$('#pronSize').value='5';startPron()};$('#randomPronWord').onclick=()=>{if(!tricky.length)return;pronDeck=[tricky[Math.floor(Math.random()*tricky.length)]];pri=0;renderPron()};

// Notebook
function renderNotebook(){const q=$('#notebookSearch').value.toLowerCase(),st=$('#notebookStatus').value;let f=TERMS.filter(t=>saved[t.word]).filter(t=>!q||JSON.stringify(t).toLowerCase().includes(q)).filter(t=>st==='all'||saved[t.word].status===st);$('#notebookResults').innerHTML=f.map(card).join('')||'<div class="panel">No saved words match these filters.</div>'}
$('#notebookSearch').oninput=renderNotebook;$('#notebookStatus').onchange=renderNotebook;$('#clearNotebook').onclick=()=>{if(confirm('Clear all saved vocabulary on this device?')){saved={};saveState();renderNotebook();renderLexicon()}};$('#exportNotebook').onclick=()=>{const rows=[['English','IPA','French','Status'],...TERMS.filter(t=>saved[t.word]).map(t=>[t.word,t.ipa,t.fr,saved[t.word].status])];const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='my-public-health-vocabulary.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};

// Progress
function updatePlan(){const vals=Object.values(saved),review=vals.filter(x=>x.status==='review').length;let title,text,page='lexicon';if(review>=5){title='Revisit your difficult vocabulary.';text=`You have ${review} saved words marked for review. A focused flashcard session is the best next step.`;page='flashcards'}else if(!activity.practice.length){title='Test active recall.';text='There is no recent practice session yet. Try five mixed questions.';page='practice'}else if(!activity.cases.length){title='Move from vocabulary to reasoning.';text='Try one Public Health Case and use the terminology in context.';page='cases'}else if(!activity.comm.length){title='Practise communicating evidence.';text='Use one Communication Lab task to turn methods and data into clear professional English.';page='communication'}else if(!activity.group.length){title='Use your English collaboratively.';text='Try one Group Activity mission: analyse the evidence, negotiate priorities and deliver a 90-second briefing.';page='groupactivity'}else if(!activity.test.length){title='Check your overall progress.';text='You have practised vocabulary and applied tasks. Take the 24-question check-up to identify your next revision target.';page='test'}else if((activity.pron||0)<5){title='Add a short pronunciation workout.';text='Practise five high-value public-health terms for stress, rhythm and intelligibility.';page='pronunciation'}else{title='Keep building your specialist vocabulary.';text='Return to the lexicon, save useful new terms and revisit them in context.';page='lexicon'}$('#planTitle').textContent=title;$('#planText').textContent=text;$('#planAction').onclick=()=>showPage(page);$('#continueLearningTitle').textContent=title;$('#continueLearningText').textContent=text;$('#continueLearningAction').onclick=()=>showPage(page)}

// Check-up
let testDeck=[],ti=0,tscore=0,testWrong=[];
function buildTest(){const chapterBuckets=Object.keys(CHAPTERS).flatMap(ch=>shuffle(TERMS.filter(t=>String(t.chapter)===ch)).slice(0,2));const extras=shuffle(TERMS.filter(t=>!chapterBuckets.includes(t))).slice(0,4);return shuffle([...chapterBuckets,...extras]).slice(0,24)}
function renderTest(){if(ti>=testDeck.length){activity.test.push({score:tscore,total:testDeck.length,date:Date.now()});testWrong.forEach(t=>{saved[t.word]=saved[t.word]||{};saved[t.word].status='review'});saveState();$('#testBox').innerHTML=`<div class="test-score"><h3>Check-up complete</h3><div class="big">${tscore}/${testDeck.length}</div><p>${tscore>=20?'Strong result. Keep using the Communication Lab and cases.':tscore>=15?'Solid base. Review the missed terms, then try again later.':'Use the missed terms as a focused revision deck.'}</p><button onclick="showPage('notebook')">Review saved words</button> <button class="primary-action" onclick="startTestRun()">Try another check-up</button></div>`;return}const t=testDeck[ti],mode=ti%3===0?'french':'definition',q=makeQ(t,mode);$('#testBox').innerHTML=`<article class="test-question"><span class="eyebrow">Question ${ti+1} / ${testDeck.length}</span><h3>${esc(q.prompt)}</h3><div class="option-grid">${q.opts.map(o=>`<button data-test-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="testFeedback"></div></article>`;$$('[data-test-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.testAnswer===q.answer;if(ok)tscore++;else testWrong.push(t);b.classList.add(ok?'correct':'wrong');$$('[data-test-answer]').forEach(x=>{if(x.dataset.testAnswer===q.answer)x.classList.add('correct');x.disabled=true});$('#testFeedback').innerHTML=`<div class="feedback"><strong>${ok?'Correct.':'Answer: '+esc(q.answer)}</strong><br><button id="nextTest">Next →</button></div>`;$('#nextTest').onclick=()=>{ti++;renderTest()}})}
function startTestRun(){testDeck=buildTest();ti=0;tscore=0;testWrong=[];renderTest()}window.startTestRun=startTestRun;$('#startTest').onclick=startTestRun;

// Accessibility & PWA
let scale=store.get('scale',1);if(typeof scale!=='number'||scale<.85||scale>1.5)scale=1;document.documentElement.style.setProperty('--scale',scale);$('#aMinus').onclick=()=>{scale=Math.max(.85,+(scale-.1).toFixed(2));document.documentElement.style.setProperty('--scale',scale);store.set('scale',scale)};$('#aPlus').onclick=()=>{scale=Math.min(1.5,+(scale+.1).toFixed(2));document.documentElement.style.setProperty('--scale',scale);store.set('scale',scale)};
function applyToggle(buttonId,on){const b=$('#'+buttonId);if(b)b.setAttribute('aria-pressed',String(Boolean(on)))}
function setDataPreference(attr,val,key,on){const root=document.documentElement;if(on)root.setAttribute(attr,val);else root.removeAttribute(attr);store.set(key,on)}
let darkOn=Boolean(store.get('a11y_dark',false)),contrastOn=Boolean(store.get('a11y_contrast',false)),simpleOn=Boolean(store.get('a11y_simple',false)),motionOn=Boolean(store.get('a11y_motion',false));setDataPreference('data-theme','dark','a11y_dark',darkOn);setDataPreference('data-contrast','high','a11y_contrast',contrastOn);document.body.classList.toggle('simple',simpleOn);document.body.classList.toggle('reduce-motion',motionOn);document.documentElement.style.scrollBehavior=motionOn?'auto':'';applyToggle('dark',darkOn);applyToggle('contrast',contrastOn);applyToggle('simple',simpleOn);applyToggle('motion',motionOn);
$('#dark').onclick=()=>{darkOn=!darkOn;setDataPreference('data-theme','dark','a11y_dark',darkOn);applyToggle('dark',darkOn)};$('#contrast').onclick=()=>{contrastOn=!contrastOn;setDataPreference('data-contrast','high','a11y_contrast',contrastOn);applyToggle('contrast',contrastOn)};$('#simple').onclick=()=>{simpleOn=!simpleOn;document.body.classList.toggle('simple',simpleOn);store.set('a11y_simple',simpleOn);applyToggle('simple',simpleOn)};$('#motion').onclick=()=>{motionOn=!motionOn;document.body.classList.toggle('reduce-motion',motionOn);document.documentElement.style.scrollBehavior=motionOn?'auto':'';store.set('a11y_motion',motionOn);applyToggle('motion',motionOn)};
function updateConnectionStatus(){const online=navigator.onLine!==false,e=$('#connectionStatus');if(!e)return;e.textContent=online?'● Online':'● Offline';e.className=online?'connection-status is-online':'connection-status'}window.addEventListener('online',updateConnectionStatus);window.addEventListener('offline',updateConnectionStatus);updateConnectionStatus();
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installApp').disabled=false;$('#headerInstallApp').disabled=false});async function install(){if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else{$('#installHelpPanel').hidden=false;showPage('home');$('#installCard').scrollIntoView({behavior:scrollBehavior()})}}$('#installApp').onclick=install;$('#headerInstallApp').onclick=install;$('#installHelp').onclick=()=>$('#installHelpPanel').hidden=!$('#installHelpPanel').hidden;if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
store.set('pronRatings',pronRatings);window.speak=speak;window.setSaved=setSaved;window.removeSaved=removeSaved;
function routeFromHash(){const hash=location.hash.replace('#','');showPage(hash&&$('#'+hash)?.classList.contains('page')?hash:'home',true)}window.addEventListener('hashchange',routeFromHash);const hash=location.hash.replace('#','');if(hash&&$('#'+hash)?.classList.contains('page'))showPage(hash,true);updateAll();

// Session 1 override for Group Activity
const SESSION1_ACTIVITY_ID='session1';
// Migrate pre-Session-1 group progress: old numeric mission IDs are no longer valid.
activity.group=(activity.group||[]).filter(x=>x===SESSION1_ACTIVITY_ID);
store.set('activity',activity);
const SESSION1_ROLES=['Access Lead','Equity Lead','Supply Lead','Innovation Lead'];
const SESSION1_BASE_SCORES={access:50,equity:50,innovation:50,sustainability:50};
const SESSION1_SCORE_LABELS={access:'Access',equity:'Equity',innovation:'Innovation',sustainability:'Sustainability'};
const SESSION1_VOCAB=['access to medicines','affordable','patent','licence','royalties','generic medicine','manufacturer','supply','mortality','low-income country'];
const SESSION1_STEPS=[
  {slug:'allocation',title:'Step 1 · Decide the allocation rule',question:'How should the first 12 million treatments be allocated?',note:'Choose the principle that will guide the first distribution round.',options:[
    {id:'A',title:'First come, first served',text:'Countries receive treatments in the order in which they place requests.',effect:{access:-4,equity:-12,innovation:4,sustainability:8},consequence:'This rule is simple to manage, but it tends to favour countries with stronger purchasing systems rather than those with the greatest health need.'},
    {id:'B',title:'Ability to pay',text:'Countries able to pay the full price receive priority access.',effect:{access:-8,equity:-18,innovation:12,sustainability:10},consequence:'Revenue is protected, but poorer settings and humanitarian populations are pushed to the back of the queue.'},
    {id:'C',title:'Health need',text:'Treatments are allocated according to mortality and disease burden.',effect:{access:8,equity:18,innovation:-2,sustainability:2},consequence:'This targets populations with the greatest health need, although some settings may still struggle to distribute treatment efficiently.'},
    {id:'D',title:'Equity first',text:'Low-resource and highly vulnerable populations receive priority access.',effect:{access:6,equity:22,innovation:-5,sustainability:-2},consequence:'This strongly reduces unfair inequalities, but the plan may be criticised by high-income buyers and can be harder to administer quickly.'},
    {id:'E',title:'Mixed allocation',text:'50% by health need, 25% by population size and 25% by delivery capacity.',effect:{access:10,equity:12,innovation:4,sustainability:12},consequence:'This balanced rule improves fairness while keeping the system workable for a range of settings.'}
  ]},
  {slug:'pricing',title:'Step 2 · Set the pricing model',question:'What pricing model should Novirex use?',note:'The original price is $780 per treatment.',options:[
    {id:'A',title:'One global price',text:'Keep the same price in every country.',effect:{access:-12,equity:-14,innovation:14,sustainability:8},consequence:'A single global price is easy to communicate, but many countries will be unable to afford the medicine.'},
    {id:'B',title:'Tiered pricing',text:'Use different prices for high-, middle- and low-income settings.',effect:{access:16,equity:13,innovation:7,sustainability:9},consequence:'Tiered pricing improves affordability while preserving some revenue from wealthier markets.'},
    {id:'C',title:'Cost-plus pricing',text:'Charge production cost plus a limited margin.',effect:{access:9,equity:8,innovation:2,sustainability:6},consequence:'This reduces prices substantially, although it may not generate enough revenue to satisfy the originator company.'},
    {id:'D',title:'Free in LMICs',text:'High-income markets cross-subsidise free access in lower-income settings.',effect:{access:20,equity:19,innovation:-10,sustainability:-2},consequence:'Access expands sharply in lower-income settings, but the model may be difficult to finance over time.'},
    {id:'E',title:'Negotiated regional prices',text:'Each region negotiates a price package separately.',effect:{access:10,equity:9,innovation:5,sustainability:4},consequence:'Regional negotiation can improve flexibility, but the process may be slow and administratively demanding.'}
  ]},
  {slug:'licence',title:'Step 3 · Choose the patent strategy',question:'What should happen to the patent and production rights?',note:'Your choice affects price, supply and innovation incentives.',options:[
    {id:'A',title:'Keep exclusive patent rights',text:'Only the originator company can produce Novirex.',effect:{access:-12,equity:-14,innovation:16,sustainability:6},consequence:'Quality control is straightforward, but supply remains limited and the medicine is likely to stay expensive.'},
    {id:'B',title:'Voluntary licence through a patent pool',text:'Create a licence similar to the Medicines Patent Pool model.',effect:{access:18,equity:15,innovation:8,sustainability:15},consequence:'This expands production, lowers prices through competition and still allows royalties to flow back to the patent holder.'},
    {id:'C',title:'Licence two selected manufacturers',text:'Approve two additional producers in selected regions.',effect:{access:10,equity:9,innovation:10,sustainability:10},consequence:'Supply improves without opening production too widely, although expansion remains slower than under a broader pooled licence.'},
    {id:'D',title:'Open licence to all qualified manufacturers',text:'Any manufacturer meeting quality standards can produce Novirex.',effect:{access:22,equity:16,innovation:-8,sustainability:-4},consequence:'Production could increase rapidly, but monitoring quality and coordinating the agreement become more complex.'},
    {id:'E',title:'Emergency licence only',text:'Use a temporary emergency mechanism limited to the current crisis.',effect:{access:14,equity:12,innovation:-12,sustainability:0},consequence:'This can improve short-term access, but it may create legal tension and uncertainty for longer-term supply planning.'}
  ]},
  {slug:'royalties',title:'Step 4 · Set the royalty model',question:'How should royalties be handled under the licence?',note:'Royalties influence both affordability and the incentive to innovate.',options:[
    {id:'A',title:'0% royalties',text:'Licensed manufacturers pay no royalties.',effect:{access:12,equity:8,innovation:-14,sustainability:-3},consequence:'Prices can fall further, but the originator company has little financial incentive to cooperate.'},
    {id:'B',title:'2% flat royalty',text:'All licensed manufacturers pay a low royalty rate.',effect:{access:10,equity:7,innovation:9,sustainability:8},consequence:'A low flat rate protects affordability while maintaining a modest revenue stream.'},
    {id:'C',title:'5% flat royalty',text:'Set a medium royalty rate across all licensed sales.',effect:{access:5,equity:3,innovation:14,sustainability:10},consequence:'The originator company is reassured, but the price reduction for buyers is smaller.'},
    {id:'D',title:'10% flat royalty',text:'Protect innovation with a high royalty rate.',effect:{access:-6,equity:-8,innovation:18,sustainability:7},consequence:'Innovation incentives are strong, but the medicine may remain too expensive for some settings.'},
    {id:'E',title:'Income-based royalties',text:'Use lower royalties in poorer countries and higher royalties in wealthier markets.',effect:{access:11,equity:10,innovation:8,sustainability:12},consequence:'This differentiated model can balance affordability and revenue, although the agreement is more complex to administer.'}
  ]},
  {slug:'manufacturing',title:'Step 5 · Build the manufacturing plan',question:'Who should manufacture Novirex?',note:'Access depends not only on price, but also on supply capacity and quality control.',options:[
    {id:'A',title:'Originator company only',text:'Keep all production with the original company.',effect:{access:-14,equity:-10,innovation:8,sustainability:6},consequence:'The system is tightly controlled, but production capacity remains too low for the global need.'},
    {id:'B',title:'One generic manufacturer',text:'Approve a single additional producer.',effect:{access:7,equity:5,innovation:2,sustainability:5},consequence:'Supply improves modestly, but one extra producer is unlikely to close the gap quickly.'},
    {id:'C',title:'Three qualified manufacturers',text:'Approve three manufacturers on different continents.',effect:{access:15,equity:11,innovation:8,sustainability:13},consequence:'This expands supply substantially while keeping quality oversight manageable.'},
    {id:'D',title:'Any qualified manufacturer',text:'Allow all manufacturers meeting quality standards to participate.',effect:{access:18,equity:12,innovation:-3,sustainability:2},consequence:'This can boost production rapidly, but coordination and quality assurance become harder.'},
    {id:'E',title:'Technology transfer to LMIC manufacturers',text:'Invest in technology transfer and regional production capacity.',effect:{access:20,equity:18,innovation:4,sustainability:10},consequence:'This strengthens long-term access and resilience, although implementation requires time and technical support.'}
  ]},
  {slug:'outbreak',title:'Step 6 · Respond to breaking news',question:'Breaking news: cases in Azania have tripled in six weeks. What should the committee do now?',note:'WHO estimates that 4 million additional treatments may soon be needed.',options:[
    {id:'A',title:'Redirect existing supplies to Azania',text:'Move doses away from other allocations immediately.',effect:{access:6,equity:15,innovation:-3,sustainability:-2},consequence:'This protects a high-mortality setting quickly, but other countries lose part of their planned allocation.'},
    {id:'B',title:'Ask countries to share their allocations',text:'Negotiate solidarity transfers from wealthier countries.',effect:{access:4,equity:12,innovation:-4,sustainability:0},consequence:'This can reduce the emergency gap, although countries may be reluctant to give up doses they have already planned to use.'},
    {id:'C',title:'Increase licensed generic production',text:'Activate emergency scale-up under the licence agreement.',effect:{access:18,equity:12,innovation:0,sustainability:7},consequence:'This addresses the surge more sustainably by expanding supply rather than merely redistributing scarcity.'},
    {id:'D',title:'Create an emergency reserve',text:'Reserve treatment for humanitarian and high-mortality settings.',effect:{access:10,equity:16,innovation:1,sustainability:10},consequence:'An emergency reserve protects the most vulnerable settings and improves preparedness for future surges.'},
    {id:'E',title:'Keep the original agreement unchanged',text:'Do not modify the existing plan.',effect:{access:-10,equity:-16,innovation:4,sustainability:6},consequence:'Administrative stability is preserved, but the agreement fails to respond to the worsening outbreak in Azania.'}
  ]}
];
let groupSession1=store.get('group_session1',{step:0,choices:[],scores:{...SESSION1_BASE_SCORES},outcome:null,completed:false});
function normaliseGroupSession1(){if(!groupSession1||typeof groupSession1!=='object')groupSession1={};if(!Array.isArray(groupSession1.choices))groupSession1.choices=[];if(typeof groupSession1.step!=='number'||groupSession1.step<0)groupSession1.step=0;const scores=groupSession1.scores||{};groupSession1.scores={access:Number.isFinite(scores.access)?scores.access:SESSION1_BASE_SCORES.access,equity:Number.isFinite(scores.equity)?scores.equity:SESSION1_BASE_SCORES.equity,innovation:Number.isFinite(scores.innovation)?scores.innovation:SESSION1_BASE_SCORES.innovation,sustainability:Number.isFinite(scores.sustainability)?scores.sustainability:SESSION1_BASE_SCORES.sustainability};groupSession1.outcome=groupSession1.outcome&&typeof groupSession1.outcome==='object'?groupSession1.outcome:null;groupSession1.completed=Boolean(groupSession1.completed);if(groupSession1.step>SESSION1_STEPS.length)groupSession1.step=SESSION1_STEPS.length}
function saveGroupSession1(){store.set('group_session1',groupSession1)}
function resetGroupSession1(){groupSession1={step:0,choices:[],scores:{...SESSION1_BASE_SCORES},outcome:null,completed:false};saveGroupSession1();renderSession1Welcome()}
function clampGroupScore(v){return Math.max(0,Math.min(100,v))}
function scoreDeltaText(v){return v>0?`+${v}`:String(v)}
function groupDecisionCode(){return groupSession1.choices.length?groupSession1.choices.join('-'):'—'}
function buildGroupScoreBoard(scores){return `<div class="group-score-board">${Object.entries(SESSION1_SCORE_LABELS).map(([key,label])=>`<div class="group-score-row"><div class="group-score-label">${label}</div><div class="group-score-bar"><div class="group-score-fill" style="width:${scores[key]}%"></div></div><div class="group-score-value">${scores[key]}</div></div>`).join('')}</div>`}
function buildImpactPills(effect){return Object.entries(effect).map(([key,val])=>`<span class="group-impact-pill ${val>0?'positive':val<0?'negative':'neutral'}">${SESSION1_SCORE_LABELS[key]} ${scoreDeltaText(val)}</span>`).join('')}
function session1Option(stepIndex,choiceId){const step=SESSION1_STEPS[stepIndex];return step?step.options.find(o=>o.id===choiceId):null}
function session1SummaryCards(){return groupSession1.choices.map((choiceId,index)=>{const step=SESSION1_STEPS[index],opt=session1Option(index,choiceId);return `<article class="group-summary-card"><span class="eyebrow">${esc(step.title)}</span><h4>${esc(opt.id+'. '+opt.title)}</h4><p>${esc(opt.text)}</p></article>`}).join('')}
function session1Profile(){const s=groupSession1.scores;if(s.access>=82&&s.equity>=82&&s.sustainability<58)return{title:'The ambitious access advocate',icon:'🌍',text:'Your plan strongly improves access and equity, but long-term financial or logistical stability remains fragile.'};if(s.innovation>=82&&s.access<60)return{title:'The innovation-first strategist',icon:'💼',text:'You protected innovation and industry confidence, but too many patients remain excluded from treatment.'};if(s.sustainability>=80&&s.access>=70&&s.equity>=70)return{title:'The balanced system builder',icon:'🏗️',text:'Your agreement combines access, fairness and feasibility in a relatively stable way.'};if(s.equity>=84)return{title:'The equity champion',icon:'⚖️',text:'You consistently prioritised populations with the greatest need and reduced unfair inequalities.'};if(s.access>=84)return{title:'The emergency responder',icon:'🚑',text:'You focused strongly on rapid expansion of access, especially in crisis settings.'};const best=Object.entries(s).sort((a,b)=>b[1]-a[1])[0][0];if(best==='sustainability')return{title:'The long-term planner',icon:'♻️',text:'Your plan emphasises durability, delivery capacity and the ability to keep the agreement working over time.'};if(best==='innovation')return{title:'The market balancer',icon:'🔬',text:'Your decisions aimed to preserve the conditions needed for future research and production.'};return{title:'The pragmatic committee',icon:'🧠',text:'Your committee tried to balance competing priorities and make a workable global agreement.'}}
function ensureSession1Completed(){if(!activity.group.includes(SESSION1_ACTIVITY_ID)){activity.group=[...new Set([...(activity.group||[]),SESSION1_ACTIVITY_ID])];saveState()}}
function renderSession1Welcome(){normaliseGroupSession1();const resume=groupSession1.choices.length&&!groupSession1.completed;const completed=groupSession1.completed;$('#groupMissionSelect').value='session1';$('#groupMissionWorkspace').innerHTML=`<article><div class="group-sim-intro"><div class="group-sim-card"><span class="eyebrow">Session 1 mission</span><h3>Design a global access agreement for Novirex.</h3><p>You will make six decisions about allocation, price, patents, royalties, manufacturing and emergency response.</p><ul class="group-steps"><li><strong>Read before you click.</strong> The option order is fixed.</li><li><strong>Discuss every choice as a team.</strong> There is no single perfect answer.</li><li><strong>Read the consequence after each decision.</strong> Your four scores will change.</li><li><strong>Use your final decision code in your briefing.</strong></li></ul><div class="session-launch-actions"><button class="primary-action" id="startSession1Btn">${completed?'↻ Start again':resume?'▶ Resume simulation':'▶ Start simulation'}</button><button id="resetSession1Btn">Reset session</button></div></div><div class="group-sim-card"><span class="eyebrow">Scoring system</span><h4>Your four targets</h4><p><strong>Access</strong> = can enough people obtain the medicine?<br><strong>Equity</strong> = are the people with the greatest need protected?<br><strong>Innovation</strong> = does the agreement preserve incentives for research?<br><strong>Sustainability</strong> = can the system work over time?</p><div class="group-decision-code">Decision code: ${esc(groupDecisionCode())}</div>${buildGroupScoreBoard(groupSession1.scores)}</div></div></article>`;$('#startSession1Btn').onclick=()=>{if(completed){groupSession1={step:0,choices:[],scores:{...SESSION1_BASE_SCORES},outcome:null,completed:false};saveGroupSession1()}startSession1Flow()};$('#resetSession1Btn').onclick=()=>{resetGroupSession1()};$('#groupMissionWorkspace').scrollIntoView({behavior:scrollBehavior(),block:'start'})}
function startSession1Flow(){normaliseGroupSession1();groupSession1.completed=false;if(groupSession1.step>=SESSION1_STEPS.length){groupSession1.step=0;groupSession1.choices=[];groupSession1.scores={...SESSION1_BASE_SCORES};groupSession1.outcome=null}saveGroupSession1();renderSession1Step()}
function renderSession1Step(){normaliseGroupSession1();if(groupSession1.completed||groupSession1.step>=SESSION1_STEPS.length){renderSession1Result();return}if(groupSession1.outcome){renderSession1Outcome();return}const step=SESSION1_STEPS[groupSession1.step];$('#groupMissionWorkspace').innerHTML=`<article><div class="group-step-meta"><span class="eyebrow">${esc(step.title)}</span><div class="group-decision-code">Decision code: ${esc(groupDecisionCode())}</div></div><h3>${esc(step.question)}</h3><p>${esc(step.note)}</p>${buildGroupScoreBoard(groupSession1.scores)}<div class="group-choice-grid">${step.options.map(o=>`<button type="button" class="group-choice-card" data-group-choice="${o.id}"><span class="choice-letter">${o.id}</span><strong>${esc(o.title)}</strong><p>${esc(o.text)}</p></button>`).join('')}</div><div class="group-step-actions"><button id="confirmGroupChoice" class="primary-action" disabled>Confirm this group choice</button><button id="backToSession1Home">Back to Session 1 overview</button></div><div id="groupChoiceHint" class="fiction-note">Discuss the options first, then confirm one shared answer for the team.</div></article>`;let selected=null;$$('[data-group-choice]').forEach(btn=>btn.onclick=()=>{selected=btn.dataset.groupChoice;$$('[data-group-choice]').forEach(x=>x.classList.toggle('selected',x===btn));$('#confirmGroupChoice').disabled=false;$('#groupChoiceHint').textContent=`Selected option: ${selected}. Confirm when the whole team agrees.`});$('#confirmGroupChoice').onclick=()=>{if(!selected)return;applySession1Choice(selected)};$('#backToSession1Home').onclick=renderSession1Welcome;$('#groupMissionWorkspace').scrollIntoView({behavior:scrollBehavior(),block:'start'})}
function applySession1Choice(choiceId){const step=SESSION1_STEPS[groupSession1.step],option=step.options.find(o=>o.id===choiceId);if(!option)return;for(const [key,val] of Object.entries(option.effect))groupSession1.scores[key]=clampGroupScore(groupSession1.scores[key]+val);groupSession1.choices[groupSession1.step]=choiceId;groupSession1.outcome={stepIndex:groupSession1.step,choiceId,consequence:option.consequence,effect:option.effect,title:option.title};saveGroupSession1();renderSession1Outcome()}
function renderSession1Outcome(){const result=groupSession1.outcome;if(!result){renderSession1Step();return}const step=SESSION1_STEPS[result.stepIndex],option=session1Option(result.stepIndex,result.choiceId);$('#groupMissionWorkspace').innerHTML=`<article><div class="group-step-meta"><span class="eyebrow">${esc(step.title)} · consequence</span><div class="group-decision-code">Decision code: ${esc(groupDecisionCode())}</div></div><h3>You chose ${esc(option.id+'. '+option.title)}</h3>${buildGroupScoreBoard(groupSession1.scores)}<div class="group-consequence-box"><strong>What happens next?</strong><p>${esc(option.consequence)}</p><div class="group-impact-pills">${buildImpactPills(option.effect)}</div></div><div class="group-step-actions"><button id="continueSession1" class="primary-action">${result.stepIndex===SESSION1_STEPS.length-1?'See final result →':'Continue to the next decision →'}</button><button id="restartSession1Mid">Restart session</button></div></article>`;$('#continueSession1').onclick=()=>{groupSession1.step=result.stepIndex+1;groupSession1.outcome=null;if(groupSession1.step>=SESSION1_STEPS.length){groupSession1.completed=true;ensureSession1Completed()}saveGroupSession1();groupSession1.completed?renderSession1Result():renderSession1Step()};$('#restartSession1Mid').onclick=()=>{resetGroupSession1()};$('#groupMissionWorkspace').scrollIntoView({behavior:scrollBehavior(),block:'start'})}
function renderSession1Result(){normaliseGroupSession1();groupSession1.completed=true;saveGroupSession1();ensureSession1Completed();const profile=session1Profile();$('#groupMissionSelect').value='session1';$('#groupMissionWorkspace').innerHTML=`<article><div class="group-profile-banner"><div class="group-profile-icon" aria-hidden="true">${profile.icon}</div><div><span class="eyebrow">Session 1 complete</span><h3>${esc(profile.title)}</h3><p>${esc(profile.text)}</p></div></div><div class="group-result-box"><div class="group-step-meta"><strong>Final decision code</strong><div class="group-decision-code">${esc(groupDecisionCode())}</div></div>${buildGroupScoreBoard(groupSession1.scores)}</div><div class="group-summary-grid">${session1SummaryCards()}</div><div class="group-briefing-grid"><div class="group-sim-card"><span class="eyebrow">Final speaking task</span><h4>Your 90-second group briefing</h4><ol class="group-steps"><li>State your main priority.</li><li>Explain one difficult trade-off.</li><li>Use the decision code to justify your plan.</li><li>Say what you would monitor next.</li></ol><div class="group-vocab-badges">${SESSION1_VOCAB.map(v=>`<span class="badge">${esc(v)}</span>`).join('')}</div></div><div class="group-sim-card"><span class="eyebrow">Teacher support</span><h4>Possible briefing structure</h4><p>“Our committee designed a global access agreement for Novirex. Our main priority was … We chose … because … The most difficult trade-off was … On balance, we recommend … We would monitor … to assess the impact of the agreement.”</p><p><small>Two teams making the same choices will always obtain the same result on any device.</small></p></div></div><div class="group-step-actions"><button id="restartSession1Final" class="primary-action">↻ Play again</button><button id="returnSession1Home">Back to Session 1 overview</button></div></article>`;$('#restartSession1Final').onclick=()=>{groupSession1={step:0,choices:[],scores:{...SESSION1_BASE_SCORES},outcome:null,completed:false};saveGroupSession1();renderSession1Step()};$('#returnSession1Home').onclick=renderSession1Welcome;$('#groupMissionWorkspace').scrollIntoView({behavior:scrollBehavior(),block:'start'})}
function drawGroupRoles(){const size=+$('#groupSize').value||4;const roles=shuffle(SESSION1_ROLES);const assigned=size===3?[roles[0],roles[1],roles[2]+' + '+roles[3]]:roles.slice(0,4);$('#groupRoleDraw').hidden=false;$('#groupRoleDraw').innerHTML=`<h3>Role draw · ${size} students</h3><div class="role-pills">${assigned.map((r,i)=>`<span class="role-pill">Student ${i+1}: ${esc(r)}</span>`).join('')}</div><p class="fiction-note">If you are only three, the last student combines two roles.</p>`}
function openSession1FromCard(){renderSession1Welcome();const target=$('#groupMissionWorkspace');if(target)target.scrollIntoView({behavior:scrollBehavior(),block:'start'})}
function initSession1GroupActivity(){normaliseGroupSession1();const select=$('#groupMissionSelect');if(select)select.innerHTML='<option value="session1">Session 1 — Who Gets the Medicine?</option>';if($('#session1CardButton'))$('#session1CardButton').onclick=openSession1FromCard;if($('#openGroupMission'))$('#openGroupMission').onclick=openSession1FromCard;if($('#randomGroupMission'))$('#randomGroupMission').onclick=()=>{groupSession1={step:0,choices:[],scores:{...SESSION1_BASE_SCORES},outcome:null,completed:false};saveGroupSession1();renderSession1Step()};if($('#drawGroupRoles'))$('#drawGroupRoles').onclick=drawGroupRoles;renderSession1Welcome()}
initSession1GroupActivity();
